node:
  switch01:
    mlag:
      address:
      backupip:
      members:
      peerip:
      sysmac:
      interfaces:
        bond01:
          clagid:
          members:
          mode:
          vlans:
    overlay:
      anycastip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp10
    lacp:
      interfaces:
        members:
    switching:
      swp10:
        mode: access
        vlans:
          - "11"
    routing:
      lo: 10.1.1.1/32
      ospf:
        area: 0
        neighbors:
          - swp1
          - swp2
      bgp:
        asn:
        underlay:
          external:
            peers:
          internal:
            peers:
      svi:
        vlan11:
          ip: 192.168.11.1/24
          vlan: "11"
          vrrp:
            mac:
            ip:
  switch02:
    mlag:
      address:
      backupip:
      members:
      peerip:
      sysmac:
      interfaces:
        bond01:
          clagid:
          members:
          mode:
          vlans:
    overlay:
      anycastip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp10
    lacp:
      interfaces:
        members:
    switching:
      swp10:
        mode: access
        vlans:
          - "22"
    routing:
      lo: 10.2.2.2/32
      ospf:
        area: 0
        neighbors:
          - swp1
          - swp2
      bgp:
        asn:
        underlay:
          external:
            peers:
          internal:
            peers:
      svi:
        vlan22:
          ip: 192.168.22.1/24
          vlan: "22"
          vrrp:
            mac:
            ip:
